# Generated by Django 4.1.7 on 2023-06-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('fecha', models.DateField()),
                ('empleador', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('profesion', models.CharField(max_length=50)),
                ('observaciones', models.CharField(max_length=200)),
            ],
        ),
    ]
