# Generated by Django 4.1.7 on 2023-06-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eval2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
